[package]
name = "learn_bevy_tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
bevy = "0.10.1"
bevy_editor_pls = "0.4.0"
bevy_rapier2d = "0.21.0"
rand = "0.8.5"
